/*
SQLyog Community v13.1.7 (64 bit)
MySQL - 10.3.28-MariaDB-cll-lve : Database - u1001166_urodatanesia
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`u1001166_urodatanesia` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `u1001166_urodatanesia`;

/*Table structure for table `kasus` */

DROP TABLE IF EXISTS `kasus`;

CREATE TABLE `kasus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pasien_id` int(11) DEFAULT NULL,
  `jenis_kasus` varchar(255) DEFAULT NULL,
  `tb` int(11) DEFAULT NULL,
  `bb` int(11) DEFAULT NULL,
  `marital_status` varchar(24) DEFAULT NULL,
  `tanggal_operasi` date DEFAULT NULL,
  `lama_perawatan_hari` int(11) DEFAULT NULL,
  `diagnosis` text DEFAULT NULL,
  `is_kasus_baru` tinyint(4) DEFAULT NULL,
  `komorbid` text DEFAULT NULL,
  `riwayat_operasi` text DEFAULT NULL,
  `penunjang_radiologi` text DEFAULT NULL,
  `penunjang_lab` text DEFAULT NULL,
  `penunjang_lab_hb` varchar(8) DEFAULT NULL,
  `penunjang_lab_ht` varchar(8) DEFAULT NULL,
  `penunjang_lab_l` varchar(8) DEFAULT NULL,
  `penunjang_lab_tr` varchar(8) DEFAULT NULL,
  `penunjang_lab_ur` varchar(8) DEFAULT NULL,
  `penunjang_lab_cr` varchar(8) DEFAULT NULL,
  `penunjang_lab_bacteria` varchar(64) DEFAULT NULL,
  `penunjang_lab_sensitive` varchar(64) DEFAULT NULL,
  `penunjang_lab_resistance` varchar(64) DEFAULT NULL,
  `ops_operator` varchar(128) DEFAULT NULL,
  `ops_tindakan_sachse` varchar(5) DEFAULT NULL,
  `ops_tindakan_bulbar_mobilisasi` varchar(5) DEFAULT NULL,
  `ops_tindakan_crucal_separasi` varchar(5) DEFAULT NULL,
  `ops_tindakan_inferior_pubektomi` varchar(5) DEFAULT NULL,
  `ops_tindakan_supercrucal_rerouting` varchar(5) DEFAULT NULL,
  `ops_tindakan_one_side_dissection` varchar(5) DEFAULT NULL,
  `ops_tindakan_johansen` varchar(5) DEFAULT NULL,
  `ops_tindakan_perineal_urethrostomy` varchar(5) DEFAULT NULL,
  `ops_tindakan_double_face` varchar(5) DEFAULT NULL,
  `ops_tindakan_ventral` varchar(5) DEFAULT NULL,
  `ops_tindakan_dorsal_onlay` varchar(5) DEFAULT NULL,
  `ops_tindakan_dorsal_inlay` varchar(5) DEFAULT NULL,
  `ops_tindakan_asopa` varchar(5) DEFAULT NULL,
  `ops_tindakan_dilatation_bougi` varchar(5) DEFAULT NULL,
  `ops_tindakan_dilatation_cold_knife` varchar(5) DEFAULT NULL,
  `ops_tindakan_dilatation_shape` varchar(5) DEFAULT NULL,
  `ops_tindakan_dilatation_laser` varchar(5) DEFAULT NULL,
  `ops_tindakan_omental_wrap` varchar(5) DEFAULT NULL,
  `ops_tindakan_non_transecting` varchar(5) DEFAULT NULL,
  `ops_tindakan_staged` varchar(5) DEFAULT NULL,
  `ops_tindakan_ventral_inlay` varchar(5) DEFAULT NULL,
  `ops_tindakan_ventral_onlay` varchar(5) DEFAULT NULL,
  `ops_tindakan_other` text DEFAULT NULL,
  `ops_graft_preputial` varchar(5) DEFAULT NULL,
  `ops_graft_penlie_skin` varchar(5) DEFAULT NULL,
  `ops_graft_cheek` varchar(5) DEFAULT NULL,
  `ops_graft_upper_lip` varchar(5) DEFAULT NULL,
  `ops_graft_lower_lip` varchar(5) DEFAULT NULL,
  `ops_graft_lingual` varchar(5) DEFAULT NULL,
  `ops_graft_gracilis` varchar(5) DEFAULT NULL,
  `ops_graft_garcilis_other` text DEFAULT NULL,
  `ops_striktur_lokasi` varchar(255) DEFAULT NULL,
  `ops_striktur_panjang` varchar(255) DEFAULT NULL,
  `ops_striktur_penyebab` varchar(255) DEFAULT NULL,
  `ops_skor_ereksi_pre_ops` tinyint(4) DEFAULT NULL,
  `ops_skor_ereksi_post_ops` tinyint(4) DEFAULT NULL,
  `ops_post_chordee` tinyint(4) DEFAULT NULL,
  `ops_panjang_penis_pre_ops` int(11) DEFAULT NULL,
  `ops_panjang_penis_post_ops` int(11) DEFAULT NULL,
  `ops_perikateter_urethrografi` varchar(255) DEFAULT NULL,
  `history_taking_date` date DEFAULT NULL,
  `trauma_type` varchar(255) DEFAULT NULL,
  `trauma_type_others` varchar(255) DEFAULT NULL,
  `etiology` text DEFAULT NULL,
  `main_complaint_pain_location` text DEFAULT NULL,
  `main_complaint_pain_location_others` text DEFAULT NULL,
  `main_complaint_haematuria` text DEFAULT NULL,
  `main_complaint_meatal_bleeding` text DEFAULT NULL,
  `main_complaint_urinary_retention` text DEFAULT NULL,
  `main_complaint_shock` text DEFAULT NULL,
  `physical_examination_gcs` text DEFAULT NULL,
  `physical_examination_shock_history` text DEFAULT NULL,
  `physical_examination_resusitation_respond` text DEFAULT NULL,
  `physical_examination_peritonitis` text DEFAULT NULL,
  `physical_examination_kidney` text DEFAULT NULL,
  `physical_examination_ureter` text DEFAULT NULL,
  `physical_examination_bladder` text DEFAULT NULL,
  `physical_examination_penile` text DEFAULT NULL,
  `physical_examination_urethra` text DEFAULT NULL,
  `physical_examination_scrotum` text DEFAULT NULL,
  `physical_examination_perianal` text DEFAULT NULL,
  `ops_indication` varchar(255) DEFAULT NULL,
  `ops_classification` varchar(255) DEFAULT NULL,
  `ops_surgery_type` varchar(255) DEFAULT NULL,
  `ops_time` varchar(255) DEFAULT NULL,
  `intraops_consult_action` text DEFAULT NULL,
  `intraops_consult_operator` text DEFAULT NULL,
  `intraops_finding` text DEFAULT NULL,
  `intraops_bleeding` text DEFAULT NULL,
  `intraops_blood_transfusion` text DEFAULT NULL,
  `intraops_surgical_technique` text DEFAULT NULL,
  `postops_death` varchar(255) DEFAULT NULL,
  `postops_death_cause` varchar(255) DEFAULT NULL,
  `postops_icu_days` varchar(255) DEFAULT NULL,
  `postops_reoperation` varchar(255) DEFAULT NULL,
  `postops_reoperation_cause` varchar(255) DEFAULT NULL,
  `postops_reoperation_days` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=568 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_anamnesis` */

DROP TABLE IF EXISTS `kasus_anamnesis`;

CREATE TABLE `kasus_anamnesis` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `main_complaint` text DEFAULT NULL,
  `main_complaint_since` text DEFAULT NULL,
  `complaint_others` text DEFAULT NULL,
  `history_of_urinarytract_stone` text DEFAULT NULL,
  `history_of_urinarytract_stone_location` text DEFAULT NULL,
  `history_of_urology_surgery` text DEFAULT NULL,
  `history_of_prostate_surgery` text DEFAULT NULL,
  `history_of_vesicolithiasis_surgery` text DEFAULT NULL,
  `karnofsky` text DEFAULT NULL,
  `iief5` text DEFAULT NULL,
  `prostatismus` text DEFAULT NULL,
  `haematuria` text DEFAULT NULL,
  `uti_symptoms` text DEFAULT NULL,
  `urinary_retention` text DEFAULT NULL,
  `dauer_cath` text DEFAULT NULL,
  `cystotomy` text DEFAULT NULL,
  `cystoscopy` text DEFAULT NULL,
  `prostate_biopsi_result` text DEFAULT NULL,
  `ipss` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=231 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_operative_intra` */

DROP TABLE IF EXISTS `kasus_operative_intra`;

CREATE TABLE `kasus_operative_intra` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `operator` text DEFAULT NULL,
  `operator_donor` text DEFAULT NULL,
  `operator_recipient` text DEFAULT NULL,
  `operation_date` date DEFAULT NULL,
  `surgical_technique` text DEFAULT NULL,
  `surgical_technique_primary_closure` text DEFAULT NULL,
  `surgical_technique_graft_stsg` text DEFAULT NULL,
  `surgical_technique_graft_ftsg` text DEFAULT NULL,
  `surgical_technique_one_stage` text DEFAULT NULL,
  `surgical_technique_two_stage` text DEFAULT NULL,
  `surgical_technique_second_stage` text DEFAULT NULL,
  `surgical_technique_position` text DEFAULT NULL,
  `surgical_technique_is_open` text DEFAULT NULL,
  `surgical_technique_open_desc` text DEFAULT NULL,
  `time` varchar(32) DEFAULT NULL COMMENT 'duration',
  `blood_loss` varchar(32) DEFAULT NULL,
  `blood_transfusion` varchar(32) DEFAULT NULL,
  `urinary_diversion_nephrostomy_pos` varchar(32) DEFAULT NULL,
  `urinary_diversion_nephrostomy_size` varchar(32) DEFAULT NULL,
  `urinary_diversion_dj_stent_pos` varchar(32) DEFAULT NULL,
  `urinary_diversion_dj_stent_size` varchar(32) DEFAULT NULL,
  `urinary_diversion_urethral_cath_pos` varchar(32) DEFAULT NULL,
  `urinary_diversion_urethral_cath_size` varchar(32) DEFAULT NULL,
  `urinary_diversion_other` text DEFAULT NULL,
  `treatment_radiotherapy` varchar(255) DEFAULT NULL,
  `treatment_chemotherapy` varchar(255) DEFAULT NULL,
  `treatment_hormonal` varchar(255) DEFAULT NULL,
  `treatment_others` text DEFAULT NULL,
  `prostate_weight` text DEFAULT NULL,
  `difficulty` text DEFAULT NULL,
  `cath_size` text DEFAULT NULL,
  `surgery_other` text DEFAULT NULL,
  `donor_kidney` text DEFAULT NULL,
  `donor_open_transperitoneal` text DEFAULT NULL,
  `donor_open_extraperitoneal` text DEFAULT NULL,
  `donor_laparoscopic_transperitoneal` text DEFAULT NULL,
  `donor_laparoscopic_extraperitoneal` text DEFAULT NULL,
  `donor_robotic_transperitoneal` text DEFAULT NULL,
  `donor_robotic_extraperitoneal` text DEFAULT NULL,
  `recipient_kidney` text DEFAULT NULL,
  `recipient_technique` text DEFAULT NULL,
  `recipient_iliaca_externa` text DEFAULT NULL,
  `recipient_iliaca_interna` text DEFAULT NULL,
  `recipient_anastomosis_end_to_end` text DEFAULT NULL,
  `recipient_anastomosis_end_to_side` text DEFAULT NULL,
  `recipient_anastomosis_side_to_side` text DEFAULT NULL,
  `urethral_implantation_extravesical` text DEFAULT NULL,
  `urethral_implantation_intravesical` text DEFAULT NULL,
  `urethral_implantation_others` text DEFAULT NULL,
  `urinary_diversion_cystostomy_size` text DEFAULT NULL,
  `urinary_diversion_ureter_cath_size` text DEFAULT NULL,
  `urinary_diversion_ureter_cath_pos` text DEFAULT NULL,
  `time_operation_ischaemic_time_warm_1` text DEFAULT NULL,
  `time_operation_ischaemic_time_cold` text DEFAULT NULL,
  `time_operation_ischaemic_time_warm_2` text DEFAULT NULL,
  `time_operation_total` text DEFAULT NULL,
  `time_operation_porting` text DEFAULT NULL,
  `solution_immersed` text DEFAULT NULL,
  `solution_flushed` text DEFAULT NULL,
  `dj_stent` tinyint(4) DEFAULT NULL,
  `dj_stent_size` text DEFAULT NULL,
  `dj_stent_pos` text DEFAULT NULL,
  `dj_stent_duration` text DEFAULT NULL,
  `cystostomy_desc` text DEFAULT NULL,
  `cystostomy_size` text DEFAULT NULL,
  `port_size` text DEFAULT NULL,
  `port_number` text DEFAULT NULL,
  `operation_site` text DEFAULT NULL,
  `finding` text DEFAULT NULL,
  `complication` text DEFAULT NULL,
  `complication_desc` text DEFAULT NULL,
  `complication_perf_desc` text DEFAULT NULL,
  `complication_intestinal_perf_desc` text DEFAULT NULL,
  `complication_hydrothorax` text DEFAULT NULL,
  `failed_procedure` text DEFAULT NULL,
  `failed_procedure_cause` text DEFAULT NULL,
  `failed_procedure_open_conversion` text DEFAULT NULL,
  `pcnl_pos` text DEFAULT NULL,
  `pcnl_time_cystocopy` text DEFAULT NULL,
  `pcnl_time_puncture` text DEFAULT NULL,
  `pcnl_time_dilatation` text DEFAULT NULL,
  `pcnl_time_lithotripsi` text DEFAULT NULL,
  `pcnl_time_dj_stent` text DEFAULT NULL,
  `pcnl_time_nefrostomy` text DEFAULT NULL,
  `pcnl_time_total_time` text DEFAULT NULL,
  `pcnl_puncture_below_costa_12` text DEFAULT NULL,
  `pcnl_puncture_above_costa_12` text DEFAULT NULL,
  `pcnl_puncture_above_costa_11` text DEFAULT NULL,
  `pcnl_puncture_type` text DEFAULT NULL,
  `pcnl_puncture_multi` text DEFAULT NULL,
  `pcnl_dilatation_type` text DEFAULT NULL,
  `pcnl_dilatation_number` text DEFAULT NULL,
  `surgical_technique_urs` text DEFAULT NULL,
  `surgical_technique_rirs` text DEFAULT NULL,
  `surgical_vesico` text DEFAULT NULL,
  `surgical_lithotripsi` text DEFAULT NULL,
  `surgical_technique_laparoscopic` text DEFAULT NULL,
  `fluoroscopy_is` text DEFAULT NULL,
  `fluoroscopy_time` text DEFAULT NULL,
  `stone_frag_pneumatic` text DEFAULT NULL,
  `stone_frag_ultrasound` text DEFAULT NULL,
  `stone_frag_laser` text DEFAULT NULL,
  `stone_frag_lowsley` text DEFAULT NULL,
  `stone_frag_stone_punch` text DEFAULT NULL,
  `stone_frag_hendrikson` text DEFAULT NULL,
  `stone_frag_no` text DEFAULT NULL,
  `rest_stone_is` text DEFAULT NULL,
  `rest_stone_type` text DEFAULT NULL,
  `rest_stone_size` text DEFAULT NULL,
  `rest_stone_plan` text DEFAULT NULL,
  `non_invasive_empiric` text DEFAULT NULL,
  `non_invasive_empiric_drug_name` text DEFAULT NULL,
  `non_invasive_hormonal` text DEFAULT NULL,
  `non_invasive_hormonal_drug_name` text DEFAULT NULL,
  `invasive_mesa` text DEFAULT NULL,
  `invasive_pesa` text DEFAULT NULL,
  `invasive_tesa` text DEFAULT NULL,
  `invasive_tese` text DEFAULT NULL,
  `invasive_anastomosis` text DEFAULT NULL,
  `urethro_sistocopy_diagnosis` text DEFAULT NULL,
  `bladder_mucosa_biopsy` text DEFAULT NULL,
  `rpg_pos` text DEFAULT NULL,
  `ureter_cath` text DEFAULT NULL,
  `nefrostomy_type` text DEFAULT NULL,
  `nefrostomy_pos` text DEFAULT NULL,
  `trauma_ureter` text DEFAULT NULL,
  `trauma_bladder` text DEFAULT NULL,
  `trauma_urethra` text DEFAULT NULL,
  `trauma_action` text DEFAULT NULL,
  `identification` text DEFAULT NULL,
  `release` text DEFAULT NULL,
  `obsgyn_operator` text DEFAULT NULL,
  `obsgyn_action` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=585 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_operative_post` */

DROP TABLE IF EXISTS `kasus_operative_post`;

CREATE TABLE `kasus_operative_post` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `wound` varchar(255) DEFAULT NULL,
  `drain` varchar(255) DEFAULT NULL,
  `urethral_cath` varchar(255) DEFAULT NULL,
  `bno` varchar(255) DEFAULT NULL,
  `complication` tinyint(4) DEFAULT NULL,
  `complication_cause` text DEFAULT NULL,
  `complication_action` text DEFAULT NULL,
  `death` tinyint(4) DEFAULT NULL,
  `death_cause` text DEFAULT NULL,
  `next_plan` text DEFAULT NULL,
  `renogram` text DEFAULT NULL,
  `micturition_urinary_retention` text DEFAULT NULL,
  `micturition_disuria` text DEFAULT NULL,
  `micturition_incontinence` text DEFAULT NULL,
  `micturition_treatment` text DEFAULT NULL,
  `orchitis` text DEFAULT NULL,
  `septic` text DEFAULT NULL,
  `uremia` text DEFAULT NULL,
  `other_disease` text DEFAULT NULL,
  `recipient_renogram` text DEFAULT NULL,
  `diet` text DEFAULT NULL,
  `vas` text DEFAULT NULL,
  `analgetics` text DEFAULT NULL,
  `analgetics_iv` text DEFAULT NULL,
  `analgetics_iv_drug` text DEFAULT NULL,
  `analgetics_oral` text DEFAULT NULL,
  `analgetics_oral_drug` text DEFAULT NULL,
  `haematoma` text DEFAULT NULL,
  `oedema_scrotum` text DEFAULT NULL,
  `wound_dehicense` text DEFAULT NULL,
  `nefrostomy_production` text DEFAULT NULL,
  `nefrostomy_production_dx` text DEFAULT NULL,
  `nefrostomy_production_sin` text DEFAULT NULL,
  `urethral_cath_production` text DEFAULT NULL,
  `cath_production` text DEFAULT NULL,
  `transfusion` text DEFAULT NULL,
  `follow_up_complaint` text DEFAULT NULL,
  `follow_up_assessment` text DEFAULT NULL,
  `follow_up_other` text DEFAULT NULL,
  `apg` text DEFAULT NULL,
  `plan_type` text DEFAULT NULL,
  `plan_duration` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=594 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_operative_pre` */

DROP TABLE IF EXISTS `kasus_operative_pre`;

CREATE TABLE `kasus_operative_pre` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `case_type` varchar(24) DEFAULT NULL,
  `diagnosis_grade` varchar(4) DEFAULT NULL,
  `diagnosis_p_infertile_nonobs_azoo` text DEFAULT NULL,
  `diagnosis_p_infertile_obs_azoo` text DEFAULT NULL,
  `diagnosis_p_infertile_sperm_type` text DEFAULT NULL,
  `diagnosis_p_infertile_sp_am_oligo` text DEFAULT NULL,
  `diagnosis_p_infertile_sp_am_astheno` text DEFAULT NULL,
  `diagnosis_p_infertile_sp_am_teratos` text DEFAULT NULL,
  `diagnosis_s_infertile_nonobs_azoo` text DEFAULT NULL,
  `diagnosis_s_infertile_obs_azoo` text DEFAULT NULL,
  `diagnosis_s_infertile_sperm_type` text DEFAULT NULL,
  `diagnosis_s_infertile_sp_am_oligo` text DEFAULT NULL,
  `diagnosis_s_infertile_sp_am_astheno` text DEFAULT NULL,
  `diagnosis_s_infertile_sp_am_teratos` text DEFAULT NULL,
  `recepient_pasien_id` int(11) DEFAULT NULL,
  `recepient_pasien_bb` text DEFAULT NULL,
  `recepient_pasien_tb` text DEFAULT NULL,
  `donor_relationship` text DEFAULT NULL,
  `etiology` text DEFAULT NULL,
  `comorbid_dm` varchar(6) DEFAULT NULL,
  `comorbid_hypertension` varchar(6) DEFAULT NULL,
  `comorbid_cardiac` varchar(6) DEFAULT NULL,
  `comorbid_heart_stroke` varchar(6) DEFAULT NULL,
  `comorbid_stroke` varchar(6) DEFAULT NULL,
  `comorbid_depression` varchar(6) DEFAULT NULL,
  `comorbid_renal` varchar(6) DEFAULT NULL,
  `comorbid_tb` varchar(6) DEFAULT NULL,
  `comorbid_ckd` varchar(6) DEFAULT NULL,
  `comorbid_premature` varchar(6) DEFAULT NULL,
  `comorbid_hypospadia` varchar(6) DEFAULT NULL,
  `comorbid_ambigous_genitalia` varchar(6) DEFAULT NULL,
  `comorbid_anorectal_malformation` varchar(6) DEFAULT NULL,
  `comorbid_down_syndrome` varchar(6) DEFAULT NULL,
  `comorbid_omphalocele` varchar(6) DEFAULT NULL,
  `comorbid_gastrosciziz` varchar(6) DEFAULT NULL,
  `comorbid_others` text DEFAULT NULL,
  `cardiac_functional` text DEFAULT NULL,
  `donor_renogram` text DEFAULT NULL,
  `ckd_etiology` text DEFAULT NULL,
  `hla_donor` text DEFAULT NULL,
  `hla_recipient` text DEFAULT NULL,
  `hla_result` text DEFAULT NULL,
  `hla_crossmatch` text DEFAULT NULL,
  `hcv_donor` text DEFAULT NULL,
  `hcv_recipient` text DEFAULT NULL,
  `cmv_donor` text DEFAULT NULL,
  `cmv_recipient` text DEFAULT NULL,
  `hiv_donor` text DEFAULT NULL,
  `hiv_recipient` text DEFAULT NULL,
  `hbsag_donor` text DEFAULT NULL,
  `hbsag_recipient` text DEFAULT NULL,
  `chromosomal_analysis` text DEFAULT NULL,
  `renogram` text DEFAULT NULL,
  `final_diagnosis` text DEFAULT NULL,
  `toxoplasma_donor` text DEFAULT NULL,
  `toxoplasma_recipient` text DEFAULT NULL,
  `igra_donor` text DEFAULT NULL,
  `igra_recipient` text DEFAULT NULL,
  `surgical_history` text DEFAULT NULL,
  `infertility_duration` text DEFAULT NULL,
  `total_child` text DEFAULT NULL,
  `semen_discharge_ejaculation` text DEFAULT NULL,
  `erection_morning` text DEFAULT NULL,
  `erection_stimulation` text DEFAULT NULL,
  `pain_post_ejaculation` text DEFAULT NULL,
  `hematospermia` text DEFAULT NULL,
  `uretritis_history` text DEFAULT NULL,
  `iritative_symptomps` text DEFAULT NULL,
  `secondary_sex_abnormalities` text DEFAULT NULL,
  `other_congenital_disease` text DEFAULT NULL,
  `scrotal_tenderness` text DEFAULT NULL,
  `inguinal_mass` text DEFAULT NULL,
  `history_udt` text DEFAULT NULL,
  `history_varicocele` text DEFAULT NULL,
  `history_trauma` text DEFAULT NULL,
  `history_genital_surgery` text DEFAULT NULL,
  `history_reccurent_uti` text DEFAULT NULL,
  `history_malignancy` text DEFAULT NULL,
  `history_others` text DEFAULT NULL,
  `history_family_infertility` text DEFAULT NULL,
  `wife_status_past_pregnancy` text DEFAULT NULL,
  `wife_status_abortion` text DEFAULT NULL,
  `wife_status_family_plan` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=295 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_penunjang` */

DROP TABLE IF EXISTS `kasus_penunjang`;

CREATE TABLE `kasus_penunjang` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `jenis` varchar(255) DEFAULT NULL,
  `path` varchar(512) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1134 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_penunjang_lab` */

DROP TABLE IF EXISTS `kasus_penunjang_lab`;

CREATE TABLE `kasus_penunjang_lab` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `jenis` varchar(255) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `lab_hb` text DEFAULT NULL,
  `lab_ht` text DEFAULT NULL,
  `lab_l` text DEFAULT NULL,
  `lab_t` text DEFAULT NULL,
  `lab_led` text DEFAULT NULL,
  `lab_diff_count` text DEFAULT NULL,
  `lab_ur` text DEFAULT NULL,
  `lab_cr` text DEFAULT NULL,
  `lab_glucose_n` text DEFAULT NULL,
  `lab_glucose_pp` text DEFAULT NULL,
  `lab_alkali_phospatase` text DEFAULT NULL,
  `lab_a_fetoprotein` text DEFAULT NULL,
  `lab_b_hcg` text DEFAULT NULL,
  `lab_ldh` text DEFAULT NULL,
  `lab_psa` text DEFAULT NULL,
  `lab_urine_eritrosit` text DEFAULT NULL,
  `lab_urine_leukosit` text DEFAULT NULL,
  `lab_urine_ph` text DEFAULT NULL,
  `lab_urine_specific_gravity` text DEFAULT NULL,
  `lab_urine_cult_pathogen` text DEFAULT NULL,
  `lab_urine_cult_bacteria` text DEFAULT NULL,
  `lab_urine_cult_sensitive` text DEFAULT NULL,
  `lab_urine_cult_resistance` text DEFAULT NULL,
  `lab_cult_urine` text DEFAULT NULL,
  `lab_cult_blood` text DEFAULT NULL,
  `lab_cult_drain` text DEFAULT NULL,
  `vessels_donor_ren_dex_artery` text DEFAULT NULL,
  `vessels_donor_ren_dex_vein` text DEFAULT NULL,
  `vessels_donor_ren_sin_artery` text DEFAULT NULL,
  `vessels_donor_ren_sin_vein` text DEFAULT NULL,
  `lab_cytology_class` text DEFAULT NULL,
  `lab_cytology_grade` text DEFAULT NULL,
  `lab_leucocyte` text DEFAULT NULL,
  `lab_trombocyte` text DEFAULT NULL,
  `lab_na` text DEFAULT NULL,
  `lab_k` text DEFAULT NULL,
  `lab_cl` text DEFAULT NULL,
  `lab_clotting_time` text DEFAULT NULL,
  `lab_bleeding_time` text DEFAULT NULL,
  `lab_tr` text DEFAULT NULL,
  `pathology_results` text DEFAULT NULL,
  `semen_volume` text DEFAULT NULL,
  `semen_sperm` text DEFAULT NULL,
  `semen_motility` text DEFAULT NULL,
  `semen_normal_shape` text DEFAULT NULL,
  `fsh` text DEFAULT NULL,
  `lh` text DEFAULT NULL,
  `testoteron` text DEFAULT NULL,
  `other` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1214 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_physical_examination` */

DROP TABLE IF EXISTS `kasus_physical_examination`;

CREATE TABLE `kasus_physical_examination` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `renal_mass` text DEFAULT NULL,
  `renal_mass_right` text DEFAULT NULL,
  `renal_mass_left` text DEFAULT NULL,
  `renal_size` text DEFAULT NULL,
  `renal_solid` text DEFAULT NULL,
  `renal_cystic` text DEFAULT NULL,
  `renal_mobile` text DEFAULT NULL,
  `renal_fixed` text DEFAULT NULL,
  `renal_pain` text DEFAULT NULL,
  `bladder_full` text DEFAULT NULL,
  `bladder_mass` text DEFAULT NULL,
  `bladder_epispadia` varchar(6) DEFAULT NULL,
  `bladder_cloacal_extrophy` text DEFAULT NULL,
  `bladder_gender` text DEFAULT NULL,
  `penis_circumcision` text DEFAULT NULL,
  `penis_mass` text DEFAULT NULL,
  `testes_udt` text DEFAULT NULL,
  `testes_size` text DEFAULT NULL,
  `testes_consistency` text DEFAULT NULL,
  `testes_hydrocele` text DEFAULT NULL,
  `testes_right_palpable` text DEFAULT NULL,
  `testes_right_size_normal` text DEFAULT NULL,
  `testes_right_size_text` text DEFAULT NULL,
  `testes_right_consistency_normal` text DEFAULT NULL,
  `testes_right_consistency_text` text DEFAULT NULL,
  `testes_right_hydrocele` text DEFAULT NULL,
  `testes_right_palpable_size` text DEFAULT NULL,
  `testes_right_palpable_pos` text DEFAULT NULL,
  `testes_right_palpable_non` text DEFAULT NULL,
  `testes_left_palpable` text DEFAULT NULL,
  `testes_left_size_normal` text DEFAULT NULL,
  `testes_left_size_text` text DEFAULT NULL,
  `testes_left_consistency_normal` text DEFAULT NULL,
  `testes_left_consistency_text` text DEFAULT NULL,
  `testes_left_hydrocele` text DEFAULT NULL,
  `testes_left_palpable_non` text DEFAULT NULL,
  `testes_left_palpable_pos` text DEFAULT NULL,
  `testes_left_palpable_size` text DEFAULT NULL,
  `testes_orkidometer_dex` text DEFAULT NULL,
  `testes_orkidometer_sin` text DEFAULT NULL,
  `testes_vol_dex` text DEFAULT NULL,
  `testes_vol_sin` text DEFAULT NULL,
  `testes_condition` text DEFAULT NULL,
  `epididimis_condition` text DEFAULT NULL,
  `epididimis_normal` text DEFAULT NULL,
  `epididimis_abnormal` text DEFAULT NULL,
  `epididimis_nodule` text DEFAULT NULL,
  `vas_deferens_condition` text DEFAULT NULL,
  `vas_deferens_normal` text DEFAULT NULL,
  `vas_deferens_abnormal` text DEFAULT NULL,
  `vas_deferens_nodule` text DEFAULT NULL,
  `urethritis` text DEFAULT NULL,
  `inguinal_gland_size` text DEFAULT NULL,
  `inguinal_gland_fixed` text DEFAULT NULL,
  `inguinal_gland_right_size_normal` text DEFAULT NULL,
  `inguinal_gland_right_size_text` text DEFAULT NULL,
  `inguinal_gland_left_size_normal` text DEFAULT NULL,
  `inguinal_gland_left_size_text` text DEFAULT NULL,
  `inguinal_gland_right_fixed_normal` text DEFAULT NULL,
  `inguinal_gland_right_fixed_text` text DEFAULT NULL,
  `inguinal_gland_left_fixed_normal` text DEFAULT NULL,
  `inguinal_gland_left_fixed_text` text DEFAULT NULL,
  `superclavicula_gland_size` text DEFAULT NULL,
  `superclavicula_gland_fixed` text DEFAULT NULL,
  `superclavicula_gland_left_size_normal` text DEFAULT NULL,
  `superclavicula_gland_left_size_text` text DEFAULT NULL,
  `superclavicula_gland_left_fixed` text DEFAULT NULL,
  `superclavicula_gland_right_size_normal` text DEFAULT NULL,
  `superclavicula_gland_right_size_text` text DEFAULT NULL,
  `superclavicula_gland_right_fixed` text DEFAULT NULL,
  `prostate_status` text DEFAULT NULL,
  `prostate_weight` text DEFAULT NULL,
  `prostate_surface` text DEFAULT NULL,
  `prostate_consistency` text DEFAULT NULL,
  `prostate_pain` text DEFAULT NULL,
  `prostate_nodul` text DEFAULT NULL,
  `cva_tenderness_right` text DEFAULT NULL,
  `cva_tenderness_left` text DEFAULT NULL,
  `vesica_urinary_tenderness` text DEFAULT NULL,
  `vesica_urinary_mass` text DEFAULT NULL,
  `urethral_meatus` text DEFAULT NULL,
  `hypospadia` text DEFAULT NULL,
  `hypospadia_site_urethral_before` text DEFAULT NULL,
  `hypospadia_site_urethral_after` text DEFAULT NULL,
  `hypospadia_prepuce` text DEFAULT NULL,
  `hypospadia_glans` text DEFAULT NULL,
  `hypospadia_chordee` text DEFAULT NULL,
  `hypospadia_urethral_plate_width` text DEFAULT NULL,
  `hypospadia_penile_torsion` text DEFAULT NULL,
  `hypospadia_scrotal_transposition` text DEFAULT NULL,
  `testes_morphology_right` text DEFAULT NULL,
  `testes_morphology_right_text` text DEFAULT NULL,
  `testes_morphology_left` text DEFAULT NULL,
  `testes_morphology_left_text` text DEFAULT NULL,
  `rectal_toucher_prostate_weight` text DEFAULT NULL,
  `rectal_toucher_surface` text DEFAULT NULL,
  `rectal_toucher_consistency` text DEFAULT NULL,
  `rectal_toucher_nodul` text DEFAULT NULL,
  `rectal_toucher_tenderness` text DEFAULT NULL,
  `hernia` tinyint(4) DEFAULT NULL,
  `haemorrhoid` tinyint(4) DEFAULT NULL,
  `classic_extrophy_male` text DEFAULT NULL,
  `classic_extrophy_female` text DEFAULT NULL,
  `epispadia` varchar(6) DEFAULT NULL,
  `child_hydro_other_complain` text DEFAULT NULL,
  `child_hydro_gender` text DEFAULT NULL,
  `child_hydro_history_antenatal_care` text DEFAULT NULL,
  `child_hydro_perinatal` text DEFAULT NULL,
  `child_hydro_developmental_status` text DEFAULT NULL,
  `child_hydro_other_congenital_status` text DEFAULT NULL,
  `child_hydro_head_dismorphic` text DEFAULT NULL,
  `child_hydro_abdominal_mass` text DEFAULT NULL,
  `child_hydro_meningocele` text DEFAULT NULL,
  `child_hydro_limb` text DEFAULT NULL,
  `child_hydro_urogical_flank` text DEFAULT NULL,
  `child_hydro_urogical_suprapubic` text DEFAULT NULL,
  `child_hydro_ext_genitalia` text DEFAULT NULL,
  `glans_hole` text DEFAULT NULL,
  `glans_shape` text DEFAULT NULL,
  `meatus_size` text DEFAULT NULL,
  `meatus_position` text DEFAULT NULL,
  `phallus_size` text DEFAULT NULL,
  `phallus_urethral_plate` text DEFAULT NULL,
  `phallus_chordee` text DEFAULT NULL,
  `torque_level` text DEFAULT NULL,
  `torque_direction` text DEFAULT NULL,
  `foreskin_hooded` text DEFAULT NULL,
  `foreskin_size` text DEFAULT NULL,
  `penoscotral_transposition` text DEFAULT NULL,
  `penis_meas_penoscrotal_junction_tip` text DEFAULT NULL,
  `penis_meas_penoscrotal_junction_meatus` text DEFAULT NULL,
  `penis_meas_meatus_tip` text DEFAULT NULL,
  `hormonal_manipulated_before_surgery` text DEFAULT NULL,
  `hypospadia_others` text DEFAULT NULL,
  `hypospadia_congenital_abnormalitis` text DEFAULT NULL,
  `hypospadia_surgical_history` text DEFAULT NULL,
  `other_congenital_abnormalities` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=267 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `kasus_uriflowmetry` */

DROP TABLE IF EXISTS `kasus_uriflowmetry`;

CREATE TABLE `kasus_uriflowmetry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kasus_id` int(11) DEFAULT NULL,
  `bulan_ke` varchar(4) DEFAULT NULL,
  `volume` int(11) DEFAULT NULL,
  `max_rate` int(11) DEFAULT NULL,
  `average_rate` int(11) DEFAULT NULL,
  `voiding_time` int(11) DEFAULT NULL,
  `flow_time` int(11) DEFAULT NULL,
  `time_to_max_flow` int(11) DEFAULT NULL,
  `position` varchar(36) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `symptomps` text DEFAULT NULL,
  `advice` text DEFAULT NULL,
  `residual_urine` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=554 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `migrations` */

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `pasien` */

DROP TABLE IF EXISTS `pasien`;

CREATE TABLE `pasien` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `no_rm` varchar(255) DEFAULT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `tanggal_lahir` date DEFAULT NULL,
  `jenis_kelamin` varchar(5) DEFAULT NULL,
  `nomor_telpon` varchar(255) DEFAULT NULL,
  `tb` int(11) DEFAULT NULL,
  `bb` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=504 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `password_resets` */

DROP TABLE IF EXISTS `password_resets`;

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `phone` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institution` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `admin` tinyint(4) DEFAULT 0,
  `active` tinyint(4) DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
